### PR TITLE
183 add job inheriting

### PR DESCRIPTION
**Pull request by YHordijk**
This now works, but we should add some test-cases

### CODE REVIEW

**Comment by SiebeLeDe** [comment]
Looks good. I am wondering does it copy the whole class? So not only the functional, basis set etc. but also dependancies or post/preamples? 

This could increase the risk of human errors for larger workflows (forgetting to get rid of certain dependancies)

**Review by SiebeLeDe — COMMENTED** [review]
See comment in the main comment review

**Comment by YHordijk** [comment]
Indeed, this will copy the whole object, but I think that should be desired behaviour in this case. If you do not want to have dependencies then the user should make sure that there is no dependency set in the reference Job object. Preambles and postambles should also be copied over in my opinion.

**Comment by SiebeLeDe** [comment]
Nice addition!

**Review by SiebeLeDe — APPROVED** [review]

**Pull request merged**
