### PR TITLE
Added the cache_file decorator

### PR DESCRIPTION
**Pull request by YHordijk**
This decorator will cache results from function calls and save them to a file locally. This is usefull for functions that are very expensive to run or require the user to be online. Previous results can then be used if the user is offline.

### CODE REVIEW

**Review by SiebeLeDe — COMMENTED** [review]
To which location is the cached file written to? I know from computer scientists that there is a certain folder called "/tmp" which is the default folder for cached files and temporary files. 

However, this is OS dependent.  

Windows: C:\Users\AppData\Local\Temp
Mac: ~/Library/Caches/

**Comment by YHordijk** [comment]
The function will create a directory called `.cached` in the tcutility `src` directory. There it will be stored as the name given by the user. Would it be better to store it in the correct caching directory?

**Comment by SiebeLeDe** [comment]
I think it's better to do it in the designated caching directory. I saw [this](https://stackoverflow.com/questions/55395893/is-there-a-standard-location-to-store-function-cache-files-in-python) through searching that could help. There is already a python package that deals with temp files called `tempfile`. Check especially the [`NamedTempFile`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile)  where you can give it a name and say if it should be deleted. 

This causes you yourself not having to deal with os dependent stuff

**Comment by YHordijk** [comment]
> I think it's better to do it in the designated caching directory. I saw [this](https://stackoverflow.com/questions/55395893/is-there-a-standard-location-to-store-function-cache-files-in-python) through searching that could help. There is already a python package that deals with temp files called `tempfile`. Check especially the [`NamedTempFile`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) where you can give it a name and say if it should be deleted.
> 
> This causes you yourself not having to deal with os dependent stuff

We now use the platformdirs module to deal with this.

**Review by SiebeLeDe — APPROVED** [review]

**Pull request merged**
